version: "3.7"

networks:
    web:
        external: true
    database: {}

services:
  mariadb:
    image: mariadb:latest
    env_file: .env
    volumes:
      - './docker-volumes/mariadb/data:/bitnami/mariadb'
    networks:
      - database

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.10
    env_file: .env
    volumes:
      - './docker-volumes/elasticsearch/config/certs:/usr/share/elasticsearch/config/certs'
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - database

  suitecrm:
    image: docker.io/bitnami/suitecrm:8
    env_file: .env
    volumes:
      - './docker-volumes/suitecrm/data:/bitnami/suitecrm'
    depends_on:
      - mariadb
    expose:
      - 80
      - 443
    networks:
      - web
      - database
    labels:
     # Caddy
     caddy: ${SUITECRM_HOST}
     caddy.reverse_proxy: "{{upstreams 8080}}"
     # Traefik
     traefik.enable: 'true'
     traefik.frontend.rule: "Host:${SUITECRM_HOST}"
     traefik.port: '8080'