version: "3.3"

networks:
  web:
      external: true

services:
  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    container_name: portainer
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - web
      - default
    labels:
     - traefik.enable=true
     - traefik.frontend.passHostHeader=true
     ## Traefik
     - traefik.portainer.backend=portainer
     - traefik.portainer.frontend.rule=Host:${PORTAINER_HOST}
     - traefik.portainer.port=9000
     - traefik.portainer.protocol=http
     ## Caddy
     - caddy.reverse_proxy.from=${PORTAINER_HOST}
     - caddy.reverse_proxy.to=http://127.0.0.1:9000
volumes:
  portainer_data: